#tomcat port
server:
  port: 9007
#jsp 
spring:
  #mvc:
    #view:
      #prefix: /WEB-INF/ipgo/
      #suffix: .jsp
  devtools:
    livereload:
      enabled: true
#mysql
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/hun?serverTimezone=Asia/Seoul
    username: angel
    password: 1234
#mybatis
mybatis:
  type-aliases-package: boot.data.mapper,boot.data.dto
  mapper-locations:
  - /mapper/**/*.xml

